base:
  background: /seafile/MyLibrary/pics/backgrounds/tree.jpg
  composing: true

bar:
  cpu: true
  ram: true
  sound: true
  date: true
  time: true

patches:
  - safefloats_patch
  - barstatus_padding

