base:
  background: /MyLibrary/pics/backgrounds/tree.jpg
  composing: true
  auto_off: mid

bar:
  cpu: false
  ram: false
  date: false
  time: false
  spacer: '                   ' 
  start: ''
  end: ''


patches:
  - safefloats_patch
  - barstatus_padding

