base:
  background: /MyLibrary/pics/backgrounds/tree.jpg
  composing: true
  auto_off: mid

bar:
  cpu: true
  ram: true
  sound: true
  date: true
  time: true

patches:
  - safefloats_patch
  - barstatus_padding

